### ISSUE TITLE
Unable to use web proxy in .Net Core

### ISSUE THREAD

**Issue by UserNotExist12** [restsharp/RestSharp#1047]
I set the proxy by this way:
![default](https://user-images.githubusercontent.com/24908144/33424242-2ad0be68-d5f6-11e7-93ed-a9ccba8b68bc.png)
## Actual Behavior
it throws an Exception...

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version: Latest
  - Platform: .Net Core 2.0
  - Subsystem:

## StackTrace
<details>

```
Operation is not supported on this platform.
   at System.Net.SystemWebProxy.GetProxy(Uri destination)
   at System.Net.ServicePointManager.ProxyAddressIfNecessary(Uri& address, IWebProxy proxy)
   at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy)
   at System.Net.HttpWebRequest.get_ServicePoint()
   at RestSharp.Http.ConfigureWebRequest(String method, Uri url) 
   at RestSharp.Http.PostPutInternal(String method) 
   at RestSharp.Http.AsPost(String httpMethod) 
   at RestSharp.RestClient.DoExecuteAsPost(IHttp http, String method)
   at RestSharp.RestClient.Execute(IRestRequest request, String httpMethod, Func`3 getResponse) 
```

</details>

**Comment by alexeyzimarev** [comment]
This is the platform limitation, not ours.
