### ISSUE TITLE
"Operation not supported on this platform" on Core 2, stable release 106.2.0

### ISSUE THREAD

**Issue by erlando** [restsharp/RestSharp#1061]
## Expected Behavior
Request should be performed

## Actual Behavior
Request is not performed. Error is encountered

## Steps to Reproduce the Problem
    var client = new RestClient("http://example.com");
    var request = new RestRequest("/", Method.GET);
    var response = client.Execute(request);
    
    // response.IsSuccessful == false, response.ErrorMessage == "Operation not supported on this platform"

## Specifications

  - Version: 106.2.0
  - Platform: .Net Core 2.0

**No proxy is defined**

## StackTrace
<details>
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.SystemWebProxy.GetProxy(Uri destination)
   at System.Net.ServicePointManager.ProxyAddressIfNecessary(Uri& address, IWebProxy proxy)
   at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy)
   at System.Net.HttpWebRequest.get_ServicePoint()
   at RestSharp.Http.ConfigureWebRequest(String method, Uri url)
   at RestSharp.Http.GetStyleMethodInternal(String method)
   at RestSharp.Http.AsGet(String httpMethod)
   at RestSharp.RestClient.DoExecuteAsGet(IHttp http, String method)
   at RestSharp.RestClient.Execute(IRestRequest request, String httpMethod, Func`3 getResponse)</details>

**Comment by erlando** [comment]
#1010

**Comment by alexeyzimarev** [comment]
I need a stack trace.

**Comment by alexeyzimarev** [comment]
Sorry, found it.

**Comment by Raylehnhoff** [comment]
I had this same issue and found this thread. Here's the stack trace from the response.ErrorException property.

There was no proxy.

Using the prior alpha version referenced in #1010 fixes this. Using the latest version does not.

````
{System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.SystemWebProxy.GetProxy(Uri destination)
   at System.Net.ServicePointManager.ProxyAddressIfNecessary(Uri& address, IWebProxy proxy)
   at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy)
   at System.Net.HttpWebRequest.get_ServicePoint()
   at RestSharp.Http.ConfigureWebRequest(String method, Uri url)
   at RestSharp.Http.GetStyleMethodInternal(String method)
   at RestSharp.Http.AsGet(String httpMethod)
   at RestSharp.RestClient.DoExecuteAsGet(IHttp http, String method)
   at RestSharp.RestClient.Execute(IRestRequest request, String httpMethod, Func`3 getResponse)}
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233031
    HelpLink: null
    InnerException: null
    Message: "Operation is not supported on this platform."
    Source: "System.Net.Requests"
    StackTrace: "   at System.Net.SystemWebProxy.GetProxy(Uri destination)
		at System.Net.ServicePointManager.ProxyAddressIfNecessary(Uri& address, IWebProxy proxy)
		at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy)
		at System.Net.HttpWebRequest.get_ServicePoint()
		at RestSharp.Http.ConfigureWebRequest(String method, Uri url)
		at RestSharp.Http.GetStyleMethodInternal(String method)
		at RestSharp.Http.AsGet(String httpMethod)
		at RestSharp.RestClient.DoExecuteAsGet(IHttp http, String method)
		at RestSharp.RestClient.Execute(IRestRequest request, String httpMethod, Func`3 getResponse)"
    TargetSite: {System.Uri GetProxy(System.Uri)}
````

**Comment by Haiping-Chen** [comment]
When I rollback to 106.1.0, it works. Hope someone will fix it for next release.

**Comment by qJake** [comment]
Having the same issue on 106.2.0.

Stack Trace:

```
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.SystemWebProxy.GetProxy(Uri destination)
   at System.Net.ServicePointManager.ProxyAddressIfNecessary(Uri& address, IWebProxy proxy)
   at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy)
   at System.Net.HttpWebRequest.get_ServicePoint()
   at RestSharp.Http.ConfigureWebRequest(String method, Uri url)
   at RestSharp.Http.GetStyleMethodInternal(String method)
   at RestSharp.Http.AsGet(String httpMethod)
   at RestSharp.RestClient.DoExecuteAsGet(IHttp http, String method)
   at RestSharp.RestClient.Execute(IRestRequest request, String httpMethod, Func`3 getResponse)
```

**Comment by granstel** [comment]
Rolling back to 106.1.0 helps me too. I've the same issue at 106.2

**Comment by alexeyzimarev** [comment]
Yeah, I admin I messed up trying to satisfy people using full framework, who lost the proxy completely. 106.2.1 fixes it. 

Hence that .NET Core will not support the default proxy. You either go without any proxy (default) or specify your own proxy by using `RestClient.Proxy` property setter.

Full framework version works as before, supporting proxy detection.

**Comment by ed-graham** [comment]
This now works for me using version 106.2.1.

**Comment by stevedorries** [comment]
Using .net core 2.1 with version 106.3.1 this issue is reoccurring for me, using version 106.2.1 fixes that.

**Comment by alexeyzimarev** [comment]
@stevedorries please post the code. Many people use 106.3.1 and it seems to be stable.

**Comment by bbougot** [comment]
Same problem here, using 106.3.1 on a ASP.NET Core 2.1 application throw a NotSupportedPlatformException while calling ExecuteTaskAsync.

**Comment by atabaksahraei** [comment]
Same here!

**Comment by DmitriiNeliubinKvk** [comment]
Same problem here.

106.4.2
netcore 2.0
Windows Server 2012 R2

```System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.SystemWebProxy.GetProxy(Uri destination)
   at System.Net.ServicePointManager.ProxyAddressIfNecessary(Uri& address, IWebProxy proxy)
   at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy)
   at System.Net.HttpWebRequest.get_ServicePoint()
   at RestSharp.Http.ConfigureWebRequest(String method, Uri url)
   at RestSharp.Http.GetStyleMethodInternal(String method)
   at RestSharp.Http.AsGet(String httpMethod)
   at RestSharp.RestClient.DoExecuteAsGet(IHttp http, String method)
   at RestSharp.RestClient.Execute(IRestRequest request, String httpMethod, Func`3 getResponse)<---```

**Comment by jeanpoelie** [comment]
Same issue here

106.5.2
netcore 2.1
Windows 10

`   at System.Net.SystemWebProxy.GetProxy(Uri destination)
   at System.Net.ServicePointManager.ProxyAddressIfNecessary(Uri& address, IWebProxy proxy)
   at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy)
   at System.Net.HttpWebRequest.get_ServicePoint()
   at RestSharp.Http.ConfigureWebRequest(String method, Uri url)
   at RestSharp.Http.PostPutInternal(String method)
   at RestSharp.Http.AsPost(String httpMethod)
   at RestSharp.RestClient.DoExecuteAsPost(IHttp http, String method)
   at RestSharp.RestClient.Execute(IRestRequest request, String httpMethod, Func`3 getResponse)`

**Comment by edmundophie** [comment]
> Same issue here
> 
> 106.5.2
> netcore 2.0
> Windows 10
> 
> `at System.Net.SystemWebProxy.GetProxy(Uri destination) at System.Net.ServicePointManager.ProxyAddressIfNecessary(Uri& address, IWebProxy proxy) at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy) at System.Net.HttpWebRequest.get_ServicePoint() at RestSharp.Http.ConfigureWebRequest(String method, Uri url) at RestSharp.Http.PostPutInternal(String method) at RestSharp.Http.AsPost(String httpMethod) at RestSharp.RestClient.DoExecuteAsPost(IHttp http, String method) at RestSharp.RestClient.Execute(IRestRequest request, String httpMethod, Func`3 getResponse)`

I upgraded to 106.5.3 and it fixes it for me.

**Comment by darroncockram** [comment]
Getting the same error with version 106.5.4 (same stack trace as above post from @jeanpoelie). This is a .NET core 2.1 app running on a Windows 10 PC.

**Comment by mrtarkhan** [comment]
same here 106.11.4
