### ISSUE TITLE
AddObject chokes on List<T>

### ISSUE THREAD

**Issue by ericnewton76** [restsharp/RestSharp#1062]
Sample code:

```c#
	public class Person { public string Name { get; set; } }

	class Program
	{
		static void Main(string[] args)
		{
			var list = new List<Person>();
			list.Add(new Person { Name = "Joe" });
			list.Add(new Person { Name = "Mary" });

			var request = new RestRequest("url");
			request.AddObject(list);

			new RestClient("http://localhost:1234").Execute(request);
		}
	}
```

## Expected Behavior
request.AddObject works without exception, just like request.AddObject(list.ToArray());

My suggestion is check if incoming object implements IEnumerable and start there with deciding how to serialize

## Actual Behavior
request.AddObject(list); //crashes

## Steps to Reproduce the Problem

  1. paste code
  2. run
  3. see exception

## Specifications

  - Version:
  - Platform:
  - Subsystem:

## StackTrace
<details>

```
System.Reflection.TargetParameterCountException occurred
  HResult=0x8002000E
  Message=Parameter count mismatch.
  Source=mscorlib
  StackTrace:
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at RestSharp.RestRequest.AddObject(Object obj, String[] includedProperties)
   at RestSharp.RestRequest.AddObject(Object obj)
   at ConsoleApp1.Program.Main(String[] args) in e:\temp\ConsoleApp1\Program.cs:line 21

```

</details>

**Comment by alexeyzimarev** [comment]
You should not use `AddObject` for your scenario. Use `AddJsonBody`.
