### ISSUE TITLE
OAuth1Authenticator for RSASHA1 on .net core 2.0 gives Operation is not supported on this platform

### ISSUE THREAD

**Issue by flipchart** [restsharp/RestSharp#1078]
This is due to the `.FromXmlString()` line in [this file](https://github.com/restsharp/RestSharp/blob/develop/RestSharp/Authenticators/OAuth/OAuthTools.cs#L347). As per [this issue](https://github.com/dotnet/core/issues/874), the xml methods of `RSACryptoServiceProvider` are not supported in .net core 2.0. I would suggest taking in an RSA instance instead of a string for `consumerSecret`, but I think a change like that is a big change to `OAuthTools`

## Expected Behavior
Successful request

## Actual Behavior
System.PlatformNotSupportedException: 'Operation is not supported on this platform.'

## Steps to Reproduce the Problem

```
var client = new RestClient("https://example.com");
client.Authenticator = OAuth1Authenticator.ForAccessToken(
	"a",
	"a",
	"a",
	"a",
	RestSharp.Authenticators.OAuth.OAuthSignatureMethod.RsaSha1
);

var request = new RestRequest();
var response = client.Execute(request);
```

## Specifications

  - Version: 106.2.1
  - Platform: Windows 10
  - Subsystem:

## StackTrace
<details>

```
   at System.Security.Cryptography.RSA.FromXmlString(String xmlString)
   at RestSharp.Authenticators.OAuth.OAuthTools.GetSignature(OAuthSignatureMethod signatureMethod, OAuthSignatureTreatment signatureTreatment, String signatureBase, String consumerSecret, String tokenSecret)
   at RestSharp.Authenticators.OAuth.OAuthWorkflow.BuildAccessTokenInfo(String method, WebParameterCollection parameters)
   at RestSharp.Authenticators.OAuth1Authenticator.AddOAuthData(IRestClient client, IRestRequest request, OAuthWorkflow workflow)
   at RestSharp.Authenticators.OAuth1Authenticator.Authenticate(IRestClient client, IRestRequest request)
   at RestSharp.RestClient.AuthenticateIfNeeded(RestClient client, IRestRequest request)
   at RestSharp.RestClient.Execute(IRestRequest request, String httpMethod, Func`3 getResponse)
   at RestSharp.RestClient.Execute(IRestRequest request)
   at CryptoTest.Program.<Main>d__0.MoveNext() in C:\work\bitbucket\CryptoTest\CryptoTest\Program.cs:line 37
```

</details>

**Comment by djanjicek** [comment]
Having the same issue. Can we do anything about it?

**Comment by alexeyzimarev** [comment]
Submit a PR?

**Comment by flipchart** [comment]
@alexeyzimarev I would be happy to send a PR for this, but wasn't sure how much you would be happy with me changing. I see 2 options:

1. For .net core, use a JSON string instead of XML for the `consumerSecret` and try to deserialize as JSON or XML using the first that suceeds
1. Change `OAuth1Authenticator` to take in an `RSACryptoServiceProvider` instance instead of a string. This would be a pretty major change to a number of service classes

Which would you prefer?

**Comment by alexeyzimarev** [comment]
Fixed by #1097

**Comment by djanjicek** [comment]
When will this fix get into a new released NuGet package?

**Comment by alexeyzimarev** [comment]
It is in the latest preview package.

**Comment by djanjicek** [comment]
Thanks. Any ETA for a stable release?

**Comment by alexeyzimarev** [comment]
Well, I am trying to get more stuff fixed. After Easter, I think.

**Comment by djanjicek** [comment]
Hi, do you have any updates on this maybe?

Thanks,
Drazen

**Comment by alexeyzimarev** [comment]
I will release during the weekend. Sorry about the delay.
