### ISSUE TITLE
Getting a unhandled 'System.Net.WebException' when calling 'ExecuteTaskAsync'

### ISSUE THREAD

**Issue by fbarnard** [restsharp/RestSharp#1084]
## Expected Behavior

Not crashing. :-)

## Actual Behavior
Crashing 

## Steps to Reproduce the Problem

all this code is inside a try/catch

 ```
var client = new RestClient(url);

            var restRequest = new RestRequest
            {
                Method = Method.POST,
                AlwaysMultipartFormData = true
            };

  var result = await client.ExecuteTaskAsync(restRequest);
```

Don know if this helps but I am connecting to WordPress REST API. And it seems like it just WordPress that is breaking.

I also, do this I am not sure where it's breaking exactly

 ```
var authenticator =
                OAuth1Authenticator.ForProtectedResource(consumerKey, consumerSecret, token, tokenSecret);
            authenticator.ParameterHandling = OAuthParameterHandling.UrlOrPostParameters;
            authenticator.SignatureMethod = OAuthSignatureMethod.HmacSha1;
            authenticator.SignatureTreatment = OAuthSignatureTreatment.Escaped;


            var client = new RestClient(url)
            {
                Authenticator = authenticator
            };

            var request = new RestRequest {Method = method};

            authenticator.Authenticate(client, request);
```

## Specifications

  - Version:105.2.3
  - Platform:Windows 10/Server 2012 r2

## StackTrace
<details>

Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.WebException
   at System.Net.HttpWebRequest.BeginGetResponse(System.AsyncCallback, System.Object)
   at RestSharp.Http.RequestStreamCallback(System.IAsyncResult, System.Action`1<RestSharp.HttpResponse>)
   at RestSharp.Http+<>c__DisplayClassa.<WriteRequestBodyAsync>b__6(System.IAsyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr)
   at System.Net.ContextAwareResult.CompleteCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Net.ContextAwareResult.Complete(IntPtr)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
   at System.Net.HttpWebRequest.InvokeGetRequestStreamCallback()
   at System.Net.HttpWebRequest.EndWriteHeaders_Part2()
   at System.Net.HttpWebRequest.EndWriteHeaders(Boolean)
   at System.Net.HttpWebRequest.WriteHeadersCallback(System.Net.WebExceptionStatus, System.Net.ConnectStream, Boolean)
   at System.Net.ConnectStream.WriteHeadersCallback(System.IAsyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr)
   at System.Net.ContextAwareResult.Complete(IntPtr)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

</details>

**Comment by alexeyzimarev** [comment]
Have you tested the call with anything else like HTTP client or just calling the API in Postman? Does it work?

**Comment by fbarnard** [comment]
Hi

Yes. It seems like the api I am calling is doing something very funky and
it is very sporadic.  I have been using rest sharp for years and that's the
first time I get something like this.

**Comment by alexeyzimarev** [comment]
Sorry but I don't think anyone can reproduce it. It is impossible to fix an issue that cannot be reproduced.
