### ISSUE TITLE
System.OutOfMemoryException getting response over 2GB .

### ISSUE THREAD

**Issue by chmirenko** [restsharp/RestSharp#1148]
## Expected Behavior
Complete execution, 

## Actual Behavior

{System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
   at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at RestSharp.Extensions.MiscExtensions.AsString(Byte[] buffer)
   at RestSharp.HttpResponse.get_Content()
   at RestSharp.RestClient.ConvertToRestResponse(IRestRequest request, HttpResponse httpResponse)
   at RestSharp.RestClient.ProcessResponse(IRestRequest request, HttpResponse httpResponse, RestRequestAsyncHandle asyncHandle, Action`2 callback)
   at RestSharp.RestClient.<>c__DisplayClass18_0.<ExecuteAsync>b__0(HttpResponse r)
   at RestSharp.Http.ExecuteCallback(HttpResponse response, Action`1 callback)
   at RestSharp.Http.<>c__DisplayClass20_0.<ResponseCallback>b__0(HttpWebResponse webResponse)
   at RestSharp.Http.GetRawResponseAsync(IAsyncResult result, Action`1 callback)
   at RestSharp.Http.ResponseCallback(IAsyncResult result, Action`1 callback)}

## Steps to Reproduce the Problem

  1. Receive a large xml response 300K large elements 
  2. Watch the memory consumption spike up to 5G
  3. Get the exception above along with:
      StatusCode: 0, Content-Type: , Content-Length: 0),
      ResponseStatus:  RestSharp.ResponseStatus.Error,
      ErrorMessage:  "Exception of type 'System.OutOfMemoryException' was thrown."

## Specifications

  - Version:
  - Platform:
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by alexeyzimarev** [comment]
You run out of memory, how do you expect us to fix this? I suppose you need to work out to get less data back.

**Comment by chmirenko** [comment]
Apologies, I submitted this one incomplete please close and advise on the detailed one.
