### ISSUE TITLE
System.OutOfMemoryException RestSharp.HttpResponse 2GB array size limit

### ISSUE THREAD

**Issue by chmirenko** [restsharp/RestSharp#1149]
## Expected Behavior

[BigArray<T>, getting around the 2GB array size limit](https://blogs.msdn.microsoft.com/joshwil/2005/08/10/bigarrayt-getting-around-the-2gb-array-size-limit/)

## Actual Behavior
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.

## Steps to Reproduce the Problem
  1. Receive a large xml response that makes RestSharp.HttpResponse grow over 2GB:
    <0x21D71930CA8>	{RestSharp.HttpResponse}	2,039,492,560	2,039,492,888 (Bytes)
  2. Watch the memory consumption spike 
  3. Get the exception below along with:
      StatusCode: 0, Content-Type: , Content-Length: 0),
      ResponseStatus:  RestSharp.ResponseStatus.Error,
      ErrorMessage:  "Exception of type 'System.OutOfMemoryException' was thrown."

## Specifications

  - Version: 1.6.19
  - Platform:  .NET Core 2.1
  - Subsystem:

## StackTrace
<details>
{System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
   at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at RestSharp.Extensions.MiscExtensions.AsString(Byte[] buffer)
   at RestSharp.HttpResponse.get_Content()
   at RestSharp.RestClient.ConvertToRestResponse(IRestRequest request, HttpResponse httpResponse)
   at RestSharp.RestClient.ProcessResponse(IRestRequest request, HttpResponse httpResponse, RestRequestAsyncHandle asyncHandle, Action`2 callback)
   at RestSharp.RestClient.<>c__DisplayClass18_0.<ExecuteAsync>b__0(HttpResponse r)
   at RestSharp.Http.ExecuteCallback(HttpResponse response, Action`1 callback)
   at RestSharp.Http.<>c__DisplayClass20_0.<ResponseCallback>b__0(HttpWebResponse webResponse)
   at RestSharp.Http.GetRawResponseAsync(IAsyncResult result, Action`1 callback)
   at RestSharp.Http.ResponseCallback(IAsyncResult result, Action`1 callback)}
</details>

**Comment by alexeyzimarev** [comment]
Is this the same as #1148?

**Comment by chmirenko** [comment]
This is the detailed one. There is an Issue with the .NET Core CLR when a collection goes over 2GB.
The post details a workaround.

**Comment by alexeyzimarev** [comment]
Thanks. But tbh I am not sure who will be fixing this except you :) It looks like an edge case. Would be nice to get a PR.

**Comment by chmirenko** [comment]
I can give it a try :) the post details how to implement a `class BigArray<T>` .
Do you think we can safetly pass this object to the xml and json serializers? that my main concern.

**Comment by alexeyzimarev** [comment]
I haven't tried working with BigArray tbh...
