### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by georgeemr** [restsharp/RestSharp#1193]
Where are using Hangfire to make some calls with restsharp. But after some time we are getting this error:

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Net.UnsafeNclNativeMethods.OSSOCK.recv(IntPtr socketHandle, Byte* pinnedBuffer, Int32 len, SocketFlags socketFlags)
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Connection.SyncRead(HttpWebRequest request, Boolean userRetrievedStream, Boolean probeRead)
   at System.Net.ConnectStream.ProcessWriteCallDone(ConnectionReturnResult returnResult)
   at System.Net.HttpWebRequest.WriteCallDone(ConnectStream stream, ConnectionReturnResult returnResult)
   at System.Net.ConnectStream.CallDone(ConnectionReturnResult returnResult)
   at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   at System.Net.ConnectStream.System.Net.ICloseEx.CloseEx(CloseExState closeState)
   at System.Net.ConnectStream.CloseInternal(Boolean internalCall)
   at System.Net.HttpWebRequest.EndWriteHeaders_Part2()
   at System.Net.HttpWebRequest.EndWriteHeaders(Boolean async)
   at System.Net.HttpWebRequest.WriteHeadersCallback(WebExceptionStatus errorStatus, ConnectStream stream, Boolean async)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   at System.Net.HttpWebRequest.EndSubmitRequest()
   at System.Net.HttpWebRequest.SetRequestSubmitDone(ConnectStream submitStream)
   at System.Net.Connection.CompleteStartRequest(Boolean onSubmitThread, HttpWebRequest request, TriState needReConnect)
   at System.Net.Connection.SubmitRequest(HttpWebRequest request, Boolean forcedsubmit)
   at System.Net.ServicePoint.SubmitRequest(HttpWebRequest request, String connName)
   at System.Net.HttpWebRequest.SubmitRequest(ServicePoint servicePoint)
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
   at RestSharp.Http.GetStyleMethodInternal(String method)
   at RestSharp.Http.AsGet(String httpMethod)
   at RestSharp.RestClient.DoExecuteAsGet(IHttp http, String method)
   at RestSharp.RestClient.Execute(IRestRequest request, String httpMethod, Func`3 getResponse)
   at RestSharp.RestClient.Execute(IRestRequest request)
   at CRDatos.Lib.Data.ExtensionMethodsCRD.ObtenerHtmlAsync(Uri pUrl, Nullable`1 TimeOut, Dictionary`2 pParametrosAfter, Dictionary`2 pParametrosBefore) in ExtensionMethods.cs:line 752
   at CRDatos.Lib.Data.AccessLayer.<VerificarColegioProfesional_Crawler>d__200.MoveNext() in AccessLayer.cs:line 2535
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at CRDatos.Lib.Data.AccessLayer.VerificarColegioProfesional_Crawler(String pCedula, ColegiosProfesionalesEntities bl, Int32 pColegioId)
   at CRDatos.Lib.Data.AccessLayer.<>c__DisplayClass202_0.<VerificarColegioProfesionalAsync>b__0(Int32 c) in AccessLayer.cs:line 2644
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at CRDatos.Lib.Data.AccessLayer.<VerificarColegioProfesionalAsync>d__202.MoveNext() in AccessLayer.cs:line 2644
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at CRDatos.Lib.Data.AccessLayer.VerificarColegioProfesionalAsync(String pCedula)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Hangfire.Server.CoreBackgroundJobPerformer.InvokeMethod(PerformContext context, Object instance, Object[] arguments)
   at Hangfire.Server.CoreBackgroundJobPerformer.Perform(PerformContext context)
   at Hangfire.Server.BackgroundJobPerformer.<>c__DisplayClass8_0.<PerformJobWithFilters>b__0()
   at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)
   at Hangfire.Server.BackgroundJobPerformer.<>c__DisplayClass8_1.<PerformJobWithFilters>b__2()
   at Hangfire.Server.BackgroundJobPerformer.PerformJobWithFilters(PerformContext context, IEnumerable`1 filters)
   at Hangfire.Server.BackgroundJobPerformer.Perform(PerformContext context)
   at Hangfire.Server.Worker.PerformJob(BackgroundProcessContext context, IStorageConnection connection, String jobId)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.InfiniteLoopProcess.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.RunProcess(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.<>c__DisplayClass1_0.<CreateTask>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.LongRunningThreadWork(Object obj)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Comment by georgeemr** [comment]
This is the method, but the app just crash without entering in the try catch.

`public static string ObtenerHtmlAsync(this Uri pUrl, int? TimeOut = null, Dictionary<string, string> pParametrosAfter = null, Dictionary<string, string> pParametrosBefore = null)
        {
            try
            {
                var client = new RestClient(string.Format("{0}://{1}", (pUrl.Port == 443) ? "https" : "http", pUrl.Host));
                client.Timeout = (TimeOut.HasValue) ? TimeOut.Value : 5000;
                client.ReadWriteTimeout = (TimeOut.HasValue) ? TimeOut.Value : 5000;
                CookieContainer _cookieCnt = new CookieContainer();
                client.CookieContainer = _cookieCnt;
                client.Encoding = Encoding.UTF8;

                var request = new RestRequest(pUrl.PathAndQuery);

                if (pParametrosAfter != null)
                    foreach (var parametro in pParametrosAfter.ToList())
                        request.AddParameter(parametro.Key, parametro.Value);

                //IRestResponse response = await Task.Factory.StartNew(() => { return client.Execute(request); });
                var response = client.Execute(request);

                if (pParametrosBefore != null)
                {
                    HtmlAgilityPack.HtmlDocument doc = new HtmlAgilityPack.HtmlDocument();
                    if (pParametrosBefore.Any(c => c.Value == null))
                        doc.LoadHtml(response.Content);
                    
                    request.Parameters.RemoveAll(c => c.Name != "Accept");
                    foreach (var parametro in pParametrosAfter.ToList())
                    {
                        if (parametro.Value == null)
                            request.AddParameter(parametro.Key, doc.GetElementbyId(parametro.Key).GetAttributeValue("value", ""));
                        else
                            request.AddParameter(parametro.Key, parametro.Value);
                    }

                    //response = await Task.Factory.StartNew(() => { return client.Execute(request); });
                    response = client.Execute(request);
                }
                var content = response.Content;             
                return response.Content;
            }
            catch (Exception e)
            {
                
            }
            return "";
        }`

**Comment by alexeyzimarev** [comment]
Well, the exception clearly says:

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

What RestSharp has to do with it?

**Comment by UweKeim** [comment]
Out of the blue, I got a similar exception:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(System.__Canon)
   at RestSharp.Extensions.StreamExtensions+<ReadAsBytes>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[RestSharp.Extensions.StreamExtensions+<ReadAsBytes>d__0, RestSharp, Version=110.2.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75]](<ReadAsBytes>d__0 ByRef)
   at RestSharp.RestResponse+<>c__DisplayClass0_0+<<FromHttpResponse>g__GetDefaultResponse|0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[RestSharp.RestResponse+<>c__DisplayClass0_0+<<FromHttpResponse>g__GetDefaultResponse|0>d, RestSharp, Version=110.2.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75]](<<FromHttpResponse>g__GetDefaultResponse|0>d ByRef)
   at RestSharp.RestResponse+<FromHttpResponse>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[RestSharp.RestResponse+<FromHttpResponse>d__0, RestSharp, Version=110.2.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75]](<FromHttpResponse>d__0 ByRef)
   at RestSharp.RestClient+<ExecuteAsync>d__0.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[RestSharp.RestClient+<ExecuteAsync>d__0, RestSharp, Version=110.2.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75]].MoveNext(System.Threading.Thread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
```

This was from a .NET 8 Console application that ran successfully for years, being updated every now and than.

The special thing about the console application was:

- Published as `<PublishSingleFile>true</PublishSingleFile>`.
- Published as `<PublishReadyToRun>true</PublishReadyToRun>`.

This also worked since ever, but on one single machine this suddenly stopped working with above exception.

I now changed the second publish option to `<PublishReadyToRun>false</PublishReadyToRun>` and now it seems it is working again.

My posting here is no complaint, just some information that might help someone some day 😊
