### ISSUE TITLE
Resharp Blocking calls

### ISSUE THREAD

**Issue by guohuang** [restsharp/RestSharp#1205]
```Blocking method has been invoked and blocked, this can lead to threadpool starvation.
         at System.Net.Http.HttpConnection.HttpContentReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
         at RestSharp.Extensions.MiscExtensions.ReadAsBytes(Stream input)
         at RestSharp.Http.ProcessResponseStream(Stream webResponseStream, HttpResponse response)
         at RestSharp.Http.ExtractResponseData(HttpResponse response, HttpWebResponse webResponse)
         at RestSharp.Http.<>c__DisplayClass20_0.<ResponseCallback>b__0(HttpWebResponse webResponse)
         at RestSharp.Http.GetRawResponseAsync(IAsyncResult result, Action`1 callback)
         at RestSharp.Http.ResponseCallback(IAsyncResult result, Action`1 callback)
         at RestSharp.Http.<>c__DisplayClass11_0.<GetStyleMethodInternalAsync>b__0(IAsyncResult result)
         at System.Net.TaskExtensions.<>c__DisplayClass0_0`1.<ToApm>b__0(Task`1 completedTask)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
         at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

I got some warning about the blocking call from RestSharp library, https://github.com/restsharp/RestSharp/blob/0c874be3b918691044f4775c041b485e134f478c/RestSharp/Http.cs#L440 maybe consider to make it async?

**Comment by alexeyzimarev** [comment]
Would be nice if you provide a better description. The stack trace is incomplete, the concent of the warning you are getting is not present and there is no code that you use that I can look at.

**Comment by guohuang** [comment]
@alexeyzimarev I don't have a solution, maybe consider using `input.ReadAsync` in this line? https://github.com/restsharp/RestSharp/blob/26e49d71079623e8ee5025fe697cd68af1053c6e/RestSharp/Extensions/MiscExtensions.cs#L52?

https://stackoverflow.com/questions/26889717/is-streamreader-read-a-blocking-method

**Comment by alexeyzimarev** [comment]
It would be great if you can provide a complete stack trace.

**Comment by guohuang** [comment]
@alexeyzimarev to give you the context, this is the tool i found the issue from, https://github.com/benaadams/Ben.BlockingDetector/issues/11#issuecomment-431380700

**Comment by guohuang** [comment]
here is the code example that I used

```            RestClient client = new RestClient(hostAddress);
            client.Timeout = DefaultInternalServiceCallTimeout;
            RestRequest request = new RestRequest(resource, method);
            request.Method = method;
            request.Parameters.AddRange(requestParameters);

            var response = await client.ExecuteTaskAsync<T>(request).ConfigureAwait(false);

            if ((int)response.StatusCode >= 200 && (int)response.StatusCode <= 299)
            {
                return JsonConvert.DeserializeObject<T>(response.Content);
            }```
