### ISSUE TITLE
Crashes after sending a request with Uri (not a string url)

### ISSUE THREAD

**Issue by maratoss** [restsharp/RestSharp#1390]
Created a test to show the problem:
https://github.com/restsharp/RestSharp/pull/1361

```cs
[Test]
public void BuildUri_should_build_with_passing_link_as_Uri()
{
	// arrange
	var relative = new Uri("/foo/bar/baz", UriKind.Relative);
	var absoluteUri = new Uri(new Uri(BASE_URL), relative);
	var req = new RestRequest(absoluteUri);
	
	// act
	var client = new RestClient();
	var builtUri = client.BuildUri(req); // <-------- crashes
	
	// assert
	Assert.AreEqual(absoluteUri, builtUri);
}
```

## Expected Behavior
Request with Url should be sent successfully

## Actual Behavior
App crashes

## Steps to Reproduce the Problem

  1. try to send a RestRequest with passing Url (not a string)
  2. gets an exception

## Specifications

  - Version: 106.6.10
  - Platform: .net framework

## StackTrace
<details>

```
System.ArgumentOutOfRangeException : Request resource doesn't contain a valid scheme for an empty client base URL
Parameter name: request
   at RestSharp.RestClient.DoBuildUriValidations(IRestRequest request) in C:\repositories\RestSharp\RestSharp\RestClient.cs:line 372
   at RestSharp.RestClient.BuildUri(IRestRequest request) in C:\repositories\RestSharp\RestSharp\RestClient.cs:line 352
   at RestSharp.Tests.RestClientTests.BuildUri_should_build_with_passing_link_as_Uri() in C:\repositories\RestSharp\RestSharp.Tests\RestClientTests.cs:line 49
```

</details>

**Comment by alexeyzimarev** [comment]
I merged your PR.
