### ISSUE TITLE
Unexpected end of MIME multipart stream. MIME multipart message is not complete.

### ISSUE THREAD

**Issue by ViachaslauSasnouski** [restsharp/RestSharp#1457]
## Expected Behavior
API parse MIME multipart body part correctly

## Actual Behavior
Error parsing MIME multipart body part.

## Steps to Reproduce the Problem

  1. Create file.txt with content:

```
HelloWorld
------
```

  2.  Send post request use `restRequest.AddFile(fileName, filePath);`
  3. Have 500 HttpStatus
![image](https://user-images.githubusercontent.com/64856524/81094011-94146c00-8f0b-11ea-93aa-ef78dbf7e761.png)

## Specifications

  - Version: 106.10.1

## StackTrace
<details>

```
System.IO.IOException: Unexpected end of MIME multipart stream. MIME multipart message is not complete.
   at System.Net.Http.Formatting.Parsers.MimeMultipartBodyPartParser.<ParseBuffer>d__0.MoveNext()
   at System.Net.Http.HttpContentMultipartExtensions.<MultipartReadAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContentMultipartExtensions.<ReadAsMultipartAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

</details>

**Comment by ViachaslauSasnouski** [comment]
PR
https://github.com/restsharp/RestSharp/pull/1458

**Comment by alexeyzimarev** [comment]
I am confused why it worked for everyone else who upload files? Are you sure it isn't a breaking change?

**Comment by ViachaslauSasnouski** [comment]
Server side error
