### ISSUE TITLE
Mock Error

### ISSUE THREAD

**Issue by sachithanandhampalaniswamy** [restsharp/RestSharp#1486]
## Expected Behavior
Should be mockable for unit testing and return mocked object
## Actual Behavior

System.NotSupportedException : Unsupported expression:....
## Steps to Reproduce the Problem

  1._moqRestClient.Setup (S => S.PostAsync<Person> (It.IsAny<IRestRequest> ())).Returns (Task.FromResult (new Person ()));

## StackTrace
<details>

  System.NotSupportedException : Unsupported expression: S => S.PostAsync<Person>(It.IsAny<IRestRequest>())
Extension methods (here: RestClientExtensions.PostAsync) may not be used in setup / verification expressions.
  Stack Trace:
     at Moq.Guard.IsOverridable(MethodInfo method, Expression expression)
   at Moq.InvocationShape..ctor(LambdaExpression expression, MethodInfo method, IReadOnlyList`1 arguments, Boolean exactGenericTypeArguments)
   at Moq.ExpressionExtensions.<Split>g__Split|4_1(Expression e, Expression& r, InvocationShape& p)
   at Moq.ExpressionExtensions.Split(LambdaExpression expression)
   at Moq.Mock.SetupRecursive[TSetup](Mock mock, LambdaExpression expression, Func`3 setupLast)
   at Moq.Mock.Setup(Mock mock, LambdaExpression expression, Condition condition)
   at Moq.Mock`1.Setup[TResult](Expression`1 expression)
</details>

**Comment by alexeyzimarev** [comment]
`PostAsync` is an extension method, so it cannot be mocked.
