### ISSUE TITLE
"Object reference not set to an instance of an object." on time-out

### ISSUE THREAD

**Issue by GieltjE** [restsharp/RestSharp#1664]
## Expected Behavior
No "Object reference not set to an instance of an object." exception but the previous "SocketException" or "WebException".
Also the timeout should be honored.

## Actual Behavior
There is an incorect exception and all subsequent requests fail.

## Steps to Reproduce the Problem

```
Task<RestResponse> requestExecuted = _client.ExecuteAsync(request, _cancellationToken);
            requestExecuted.ContinueWith(response =>
 { ... }
```

Be sure to call something that takes longer than the request timeout.

## Specifications

  - Version: 107.0.0-preview.4
  - Platform: .NET 4.8, X64

## StackTrace
<details>

   at RestSharp.HttpContentExtensions.GetFormBoundary(HttpContent content)
   at RestSharp.RequestContent.GetContentTypeHeader(String contentType)
   at RestSharp.RequestContent.<AddHeaders>g__AddHeader|15_1(Parameter parameter)
   at RestSharp.Extensions.CollectionExtensions.ForEach[T](IEnumerable`1 items, Action`1 action)
   at RestSharp.RequestContent.BuildContent()
   at RestSharp.RestClient.<ExecuteInternal>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestSharp.RestClient.<ExecuteAsync>d__0.MoveNext()

</details>

**Comment by alexeyzimarev** [comment]
Thanks for reporting this. Keep in mind that `SocketException` or `WebException` won't be produced anymore, you should expect `HttpRequestException` instead.

Request timeout should work, we have tests for it.

**Comment by alexeyzimarev** [comment]
Could you also post the request config? I don't see how this exception could happen under normal circumstances.

**Comment by alexeyzimarev** [comment]
Btw this exception has nothing to do with the timeout. You could've noticed from the stack trace that it throws _before_ making a request.

**Comment by alexeyzimarev** [comment]
As there's no follow up on this issue I am closing it.

**Comment by GieltjE** [comment]
After debugging with the latest dev source, there was a more helpfull message: "Content headers should not be used when there's no body in the request"

As the otherside does require the headers we're now simply adding an empty body which seems to work just fine.

```   at RestSharp.RequestContent.AddHeaders() in C:\Users\MichielHazelhof\Desktop\RestSharp-dev\src\RestSharp\Request\RequestContent.cs:line 148
   at RestSharp.RequestContent.BuildContent() in C:\Users\MichielHazelhof\Desktop\RestSharp-dev\src\RestSharp\Request\RequestContent.cs:line 41
   at RestSharp.RestClient.<ExecuteInternal>d__1.MoveNext() in C:\Users\MichielHazelhof\Desktop\RestSharp-dev\src\RestSharp\RestClient.Async.cs:line 40
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RestSharp.RestClient.<ExecuteAsync>d__0.MoveNext() in C:\Users\MichielHazelhof\Desktop\RestSharp-dev\src\RestSharp\RestClient.Async.cs:line 12
```

**Comment by alexeyzimarev** [comment]
Yeah, I added the exception. If you figure out how to avoid this exception, please feel free to contribute.

The reason for this is that `Content-Type` is the content header, but without a request body, there's no content, so there's nothing to add content headers to.

**Comment by alexeyzimarev** [comment]
What do you use as an empty body?

I changed the code to be like this, maybe you can try it out

```csharp
        if (contentHeaders.Length > 0 && Content == null) {
            // We need some content to add content headers to it, so if necessary, we'll add empty content
            Content = new StringContent("");
        }
```

**Comment by GieltjE** [comment]
Thanks, that patch seems to work just fine, it's basically the same as what I've added (just for everyone).
