### ISSUE TITLE
Receive MethodNotAllowed in v107

### ISSUE THREAD

**Issue by dcdraper** [restsharp/RestSharp#1707]
**DO NOT USE ISSUES FOR QUESTIONS**

**Describe the bug**
I am attempting a POST request in v107 that used to work before v107. See https://stackoverflow.com/questions/70686539/v107-getting-status-code-of-methodnotallowed-on-a-post-request-that-used-to-work for details. As suggested by Alexey there I have re-written some code and now I get an exception with MethodNotAllowed, rather than a response with status - MethodNotAllowed.

**To Reproduce**
Reworked Code:
`
//constructor
public MerlinServiceBase()
        {
            GetCreds();
            _authClient = new RestClient(_authUrl);
            _authClient.Authenticator = new HttpBasicAuthenticator(_authClientId, _authClientSecret);
        }

private async System.Threading.Tasks.Task<string> GetAuthTokenAsync()
        {
            var request = new RestRequest()
                .AddParameter("grant_type", "client_credentials");
            var response = await _authClient.PostAsync<Dictionary<string, string>>(request);
            return response["access_token"];
        }
`

**Expected behavior**
I expected to get an auth token

**Stack trace**
System.Net.Http.HttpRequestException
  HResult=0x80131500
  Message=Request failed with status code MethodNotAllowed
  Source=RestSharp
  StackTrace:
   at RestSharp.RestClientExtensions.<PostAsync>d__11`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RentalWebClient.V3.QA.Automation.UI.MerlinServiceBase.<GetAuthTokenAsync>d__10.MoveNext() in C:\Source\OpenTech\Kiosk\Ota.Kiosk.RentalWebClient.V3.QA.Automation\RentalWebClient.V3.QA.Automation.UI\_Merlin API\Merlin_ServiceBase.cs:line 87

  This exception was originally thrown at this call stack:
    [External Code]
    RentalWebClient.V3.QA.Automation.UI.MerlinServiceBase.GetAuthTokenAsync() in Merlin_ServiceBase.cs

**Desktop (please complete the following information):**
 - OS: Windows 10
 - .NET Framework 4.7.2

**Additional context**
Please let me know what other details I could add.

**Comment by alexeyzimarev** [comment]
In my SO answer I suggested tracing the request so you can understand why you get this response. It is not RestSharp that returns the "method not allowed response", it is the server. It is only possible to find what the issue is if you can compare the actual request made by RS 107 and a working request. In my answer, I admitted that I don't see obvious issues in the code, and I suggested some improvements, but I wasn't really expecting it to work, honestly.

**Comment by alexeyzimarev** [comment]
MDN also suggests:

> The server must generate an Allow header field in a 405 status code response. The field must contain a list of methods that the target resource currently supports.

Response headers are available if you use `ExecutePostAsync<T>` as part of `RestResponse`. If you inspect the `Allow` header value returned by the server, you can understand the reason for error better,

**Comment by alexeyzimarev** [comment]
Btw, I think you are trying to get the access token from an OAuth2 authorisation server. It's irrelevant for the issue, but it could be easier to deserialize the response to a proper object instead of using the dictionary. The response format is well-known:

```
HTTP/1.1 200 OK
Content-Type: application/json
Cache-Control: no-store
 
{
  "access_token":"MTQ0NjJkZmQ5OTM2NDE1ZTZjNGZmZjI3",
  "token_type":"Bearer",
  "expires_in":3600,
  "refresh_token":"IwOGYzYTlmM2YxOTQ5MGE3YmNmMDFkNTVk",
  "scope":"create"
}
```

**Comment by dcdraper** [comment]
The Allow Header said Get, but that is not how I did it before, it was always Post. When I try Get I get a Bad Request response.

Do you have a working example for 107 with OAuth2?  I am totally stuck here without being to auth first.  I wish I had time at work to figure out how to use that tracer but I do not at the moment.  

This RestSharp update is going to require lots of changes to our automation projects and I really just need to stay on the lower version for now until I can find help.

**Comment by alexeyzimarev** [comment]
An example for OAuth2 would be problematic as most of the vendors use their own deviations. Unlike OAuth1, which is very strict, OAuth2 is quite relaxed in terms of what headers are used, etc.

Do you have any docs of the server you are trying to call? Can you post it here? Maybe that can help.

**Comment by dcdraper** [comment]
We use Amazon Cognito with client_credentials: https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html

I am still trying stuff here and there, learning about and finding my way around the the new and old layouts of the client and response objects. A minor thing I noticed is that Resource is set to "" instead of null on the new RestRequest object, but moving "/token" to there from my base url seemed to not help (or hurt) at all.

**Comment by alexeyzimarev** [comment]
I created a simple Twitter client with a custom authenticator. It appears that Twitter OAuth2 token endpoint works the same way as the one you're using. I had no issues with it.

https://gist.github.com/alexeyzimarev/62d77bb25d7aa5bb4b9685461f8aabdd

**Comment by dcdraper** [comment]
I will try the example but I cannot use the C# version you are using in my projects since we require .NET Framework not Core.  Where can I get RestSharp.Tests.External.Tools?

**Comment by alexeyzimarev** [comment]
The snippet doesn't work with Cognito, I tried. I have no idea why. The only way to find out is to inspect the full request content in a working version and the not-working version. I am sorry but I spent a couple of hours yesterday on this already.

The Tools namespace contains the `OutputLogger`. You don't need it.

**Comment by alexeyzimarev** [comment]
Btw it is easy to compare requests using a tool like https://requestbin.com.

Here, for example, is the request made with RS 107 using the authoriser I've built:

![image](https://user-images.githubusercontent.com/2821205/150088683-866547e3-2635-45df-8f58-459ab08a3fc8.png)

**Comment by alexeyzimarev** [comment]
Same using your code from SO for RS 106

![image](https://user-images.githubusercontent.com/2821205/150098053-42ba22fd-e168-44b3-bcc7-a024740e102e.png)

**Comment by alexeyzimarev** [comment]
Basically, Cognito is picky about `Accept` content types. The code below fixes it:

```csharp
        using var client = new RestClient(options) {
            Authenticator = new HttpBasicAuthenticator(_clientId, _clientSecret),
            AcceptedContentTypes = new []{"application/json", "text/json", "text/x-json", "text/javascript"}
        };
```

I am looking to improving the `Accept` header content.

**Comment by dcdraper** [comment]
That fixed it :)
Thank you so much for spending so much of your valuable time on it, it is appreciated!
