### ISSUE TITLE
Can not get content of BadRequest response 

### ISSUE THREAD

**Issue by phoeson** [restsharp/RestSharp#1721]
**Describe the bug**
Response like:
HTTP/1.1 400 Bad Request
Server: nginx
Date: Tue, 25 Jan 2022 07:25:58 GMT
Content-Type: application/json
Content-Length: 52
Connection: keep-alive
Access-Control-Allow-Origin: *

{"message":"Value for 'source_lang' not supported."}

For server response with 400 status, it throws HttpRequestException, so it is not able to get the content of the response for details about service message

**To Reproduce**
General behavior

**Expected behavior**
To get the response object for details info to handle by developer

**Stack trace**
   at RestSharp.RestClientExtensions.<PostAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ServiceProcessor.Service.TranslatesService.<Post>d__2.MoveNext()

**Desktop (please complete the following information):**
 - OS: [e.g. Win 10]
 - .NET version [NET 4.8]
 - Version [107.1.1]

**Comment by alexeyzimarev** [comment]
So, where's the code?
