### ISSUE TITLE
Exception While Reading Response Headers

### ISSUE THREAD

**Issue by toddca** [restsharp/RestSharp#1772]
I recently upgrade my application from Net5 to Net6 as well as RestSharp to 107.3.0. I have run into issues (stack below) while using this library to access a few totally unrelated REST services. Looking at the Git for this project I believe I have tracked down the method for which the exception is being thrown to: https://github.com/restsharp/RestSharp/blob/fc27aef8305ec32ae73ccccc9afae266197b0ac6/src/RestSharp/Extensions/HttpHeadersExtensions.cs#L21 which is an extension method GetHeaderParameters() however I am unclear why accessing the HttpHeaders in this manner would throw this exception. My first thought was the Http Headers being returned where malformed however this is occuring accross at leat two different and unrelated REST based services.  

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at System.Net.Http.Headers.HttpHeaders.ReadStoreValues[T](Span`1 values, Object storeValue, HttpHeaderParser parser, Int32& currentIndex)
at System.Net.Http.Headers.HttpHeaders.GetStoreValuesAsStringOrStringArray(HeaderDescriptor descriptor, Object sourceValues, String& singleValue, String[]& multiValue)
at System.Net.Http.Headers.HttpHeaders.GetEnumeratorCore()+MoveNext()
at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
at RestSharp.RestResponse.<>c__DisplayClass0_0.<g__GetDefaultResponse|0>d.MoveNext()
--- End of stack trace from previous location ---
at RestSharp.RestResponse.<>c__DisplayClass0_0.<g__GetDefaultResponse|0>d.MoveNext()
--- End of stack trace from previous location ---
at RestSharp.RestResponse.FromHttpResponse(HttpResponseMessage httpResponse, RestRequest request, Encoding encoding, CookieCollection cookieCollection, CalculateResponseStatus calculateResponseStatus, CancellationToken cancellationToken)
at RestSharp.RestClient.ExecuteAsync(RestRequest request, CancellationToken cancellationToken)
at Bond.Clients.Rest.BaseRestClient.<>c__DisplayClass26_0`1.<b__0>d.MoveNext() in C:\agent\_work\1\s\Bond\src\Bond.Clients\Rest\BaseRestClient.cs:line 120
--- End of stack trace from previous location ---
at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
at Bond.Clients.Rest.BaseRestClient.ExecuteAsync[T](RestRequest request, Boolean throwIfError, CancellationToken cancellationToken) in C:\agent\_work\1\s\Bond\src\Bond.Clients\Rest\BaseRestClient.cs:line 0
at Bond.Annaware.Clients.OrdersClient.GetByOrderGuidAsync(Guid guid, CancellationToken cancellationToken) in C:\agent\_work\1\s\Bond\src\Bond.Annaware\Clients\OrdersClient.cs:line 44
at Bond.Commerce.Services.Annaware.AnnawareWebServiceRepository.GetOrderByUniqueIdAsync(String uniqueId, CancellationToken cancellationToken) in C:\agent\_work\1\s\Bond\src\Bond.Commerce\Services\Annaware\AnnawareWebServiceRepository.cs:line 157
at Bond.Commerce.Services.Annaware.AnnawareOrderLookupService.InternalGetAnnawareOrderAsync(Guid id) in C:\agent\_work\1\s\Bond\src\Bond.Commerce\Services\Annaware\AnnawareOrderLookupService.cs:line 277
```

**Comment by toddca** [comment]
The issue may be related to this net6 issue: #https://github.com/dotnet/runtime/issues/61798

**Comment by MihaZupan** [comment]
Any chance you are using NewRelic in the process / on the host machine?

**Comment by toddca** [comment]
@MihaZupan in fact yes, it is running on this particular site. I have disabled the agent for this site and monitoring to see if this happens again sans NewRelic.

**Comment by MihaZupan** [comment]
This has been resolved if you update their agent to  v9.2.0+ (https://github.com/newrelic/newrelic-dotnet-agent/issues/803)

**Comment by alexeyzimarev** [comment]
@toddca shall I keep it open?

**Comment by toddca** [comment]
Please close - upgrading the NewRelic agent fixed.
