### ISSUE TITLE
An error occurred while sending the request

### ISSUE THREAD

**Issue by my522cn** [restsharp/RestSharp#1853]
When sending post request, this exception was catched occasionally. How to fix this bug?
`System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at RestSharp.RestClient.ExecuteAsync(RestRequest request, CancellationToken cancellationToken)
   at RestSharp.RestClientExtensions.PostAsync(RestClient client, RestRequest request, CancellationToken cancellationToken)
   at X1149Log.Case.Lenovo_L2.Server.GetTokenAsync()|An error occurred while sending the request.`

My Code:
```Csharp
var options = new RestClientOptions($"https://xxxxx")
{
    ThrowOnAnyError = true,
    Timeout = _settings.Timeout,
    RemoteCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) => true,   
};
var client = new RestClient(options, headers => headers.ConnectionClose = true);
var request = new RestRequest().AddBody(sendmsg);
var response = await client.PostAsync(request);
```

**Comment by ajeyaprakash148** [comment]
if the below code is in a foreach and if you are making too many requests sequentially in a short time there is a possibility of the mentioned error. You can review this scenario.

var client = new RestClient(options, headers => headers.ConnectionClose = true);
