### ISSUE TITLE
Request failed with status code BadGateway

### ISSUE THREAD

**Issue by Eugene-Lytvynov** [restsharp/RestSharp#1877]
**DO NOT USE ISSUES FOR QUESTIONS**

**Describe the bug**
During sending request we got an error some times: 
System.Net.Http.HttpRequestException: Request failed with status code BadGateway
 
We use concurrency semaphore 10 counts limit, and loop over 3000 item with connection to https api server, IIS 10. 

Agent - default, request timeout - default. we reuse restsharp client in loop for, but we create an request as instance for every request. We use cancellation timeout 15 sec for each operation and 1h cancellation for whole process.

We use this logic as a script, and it make error for time to time, for example 1 time in 4 hours

**To Reproduce**
1. create rest sharp
2. create loop over 3000 task
3. in loop recreate request with cancelation token:15 min
4. run loop aver 3000 with cancelation token 1h and semaphore 10 tasks.

**Expected behavior**
Not get this error or explanation why it happens 

**Stack trace**
System.Net.Http.HttpRequestException: Request failed with status code BadGateway
   at RestSharp.RestClient.ThrowIfError(RestResponse response)
   at RestSharp.RestClientExtensions.GetAsync(RestClient client, RestRequest request, CancellationToken cancellationToken)

**Desktop (please complete the following information):**
 - OS: Windows server
 - .NET version 5.1
 - Version [107.3.0]

**Additional context**

**Comment by Eugene-Lytvynov** [comment]
Looks like we found: reason the WAF. Looks like it block some requests.
