### ISSUE TITLE
RemoteCertificateValidationCallback does not seem to work on v107

### ISSUE THREAD

**Issue by paulo-j-m-nunes** [restsharp/RestSharp#1884]
Ignoring SSL certificate validation errors by setting the RemoteCertificateValidationCallback callback, as follows, does not seem to work:

var options = new RestClientOptions(baseurl) {
    RemoteCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) => true;
};
var restClient = new RestClient(options);

In v106 this could be done at application level as follows:

ServicePointManager.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => true;

StackTrace:

<html>
<body>

System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.)
--
Mon, Jul 4 2022 1:03:48 pm | ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
Mon, Jul 4 2022 1:03:48 pm | ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: PartialChain
Mon, Jul 4 2022 1:03:48 pm | at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
Mon, Jul 4 2022 1:03:48 pm | at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
Mon, Jul 4 2022 1:03:48 pm | at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
Mon, Jul 4 2022 1:03:48 pm | --- End of inner exception stack trace ---
Mon, Jul 4 2022 1:03:48 pm | at RestSharp.RestClientExtensions.PostAsync(RestClient client, RestRequest request, CancellationToken cancellationToken)

</body>
</html>

 - OS: aspnet:5.0-alpine image
 - .NET 5
 - Version 107.0.3

**Comment by paulo-j-m-nunes** [comment]
Not applicable. It works.
