### ISSUE TITLE
HttpClient.Timeout of 100 seconds elapsing after upgrade from 106.15.0 to 108.0.2.

### ISSUE THREAD

**Issue by lasbrojen** [restsharp/RestSharp#1944]
Hi 😊

We just upgraded RestSharp from 106.15.0 to 108.0.2.

After the upgrade, we often get the error below.

On the screenshot you can see how we use RestSharp.

![image](https://user-images.githubusercontent.com/5829905/196406482-d740f095-a15c-4f41-a294-e80587b2f981.png)

**Environment**
- C# Console Application
- .Net 6
- Running on Windows Server 2022

**Error:**
```
"The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.", Exception: 
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
```

Thank you for a great project 👍

BR
LasBroJen

**Comment by ManikandanMani** [comment]
I too face the same issue

**Comment by lasbrojen** [comment]
Thank you @nesc58 it works. I no longer get the the error😊👍

I thought the below would work 😊

![196406482-d740f095-a15c-4f41-a294-e80587b2f981](https://user-images.githubusercontent.com/5829905/204635377-09d8e030-46f5-40db-a1a0-5d0f204bb098.png)
