### ISSUE TITLE
mediaType null or empty when using RestSharp 108.0.2 with .NET 7

### ISSUE THREAD

**Issue by cheindel** [restsharp/RestSharp#1969]
![Bildschirm­foto 2022-11-09 um 22 55 56](https://user-images.githubusercontent.com/454595/200951871-3b4897dc-0d98-459f-9717-3fa0703c9514.png)
**Describe the bug**

After changing target framework from .NET 6 to .NET 7 the following code in a Blazor server side application started to throw an exception (no matter if individual packages are referenced using their 6.0.10 or 7.0.0 versions):

var request = new RestRequest(BaseUrl + "waitinglist/" + accessToken);
request.AddParameter("officeNumber", PracticeId);
request.AlwaysMultipartFormData = true;
request.Method = Method.Post;
var response = client.ExecuteAsync(request);

Once I change target framework back to .NET 6, it works again.

**To Reproduce**
See description above and screenshot attached

**Expected behavior**
No exception but results returned.

**Stack trace**
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: The value cannot be null or empty. (Parameter 'mediaType')

System.ArgumentException: The value cannot be null or empty. (Parameter 'mediaType')
   at System.Net.Http.Headers.MediaTypeHeaderValue.CheckMediaTypeFormat(String mediaType, String parameterName)
   at System.Net.Http.StringContent..ctor(String content, Encoding encoding, String mediaType)
   at RestSharp.RequestContent.AddPostParameters(ParametersCollection postParameters)
   at RestSharp.RequestContent.BuildContent()
   at RestSharp.RestClient.ExecuteInternal(RestRequest request, CancellationToken cancellationToken)
   at RestSharp.RestClient.ExecuteAsync(RestRequest request, CancellationToken cancellationToken)
   at DPAForPRODUCTNAMEREMOVEDBlazor.Controllers.PRODUCTNAMEREMOVED.DownloadPRODUCTNAMEREMOVEDJSON(Boolean forceDownload) in /Users/christian/projects/Insights-and-Services-for-PRODUCTNAMEREMOVED/DPAForPRODUCTNAMEREMOVEDBlazor/Controllers/PRODUCTNAMEREMOVED.cs:line 297
   at DPAForPRODUCTNAMEREMOVEDBlazor.Controllers.PRODUCTNAMEREMOVED.DownloadPRODUCTNAMEREMOVEDJSON() in /Users/christian/projects/Insights-and-Services-for-PRODUCTNAMEREMOVED/DPAForPRODUCTNAMEREMOVEDBlazor/Controllers/PRODUCTNAMEREMOVED.cs:line 198
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '3hFrvBILVAv_71c7LL_TtxPkV0PGJNviJWzjwzYOQgQ'.
      System.ArgumentException: The value cannot be null or empty. (Parameter 'mediaType')
         at System.Net.Http.Headers.MediaTypeHeaderValue.CheckMediaTypeFormat(String mediaType, String parameterName)
         at System.Net.Http.StringContent..ctor(String content, Encoding encoding, String mediaType)
         at RestSharp.RequestContent.AddPostParameters(ParametersCollection postParameters)
         at RestSharp.RequestContent.BuildContent()
         at RestSharp.RestClient.ExecuteInternal(RestRequest request, CancellationToken cancellationToken)
         at RestSharp.RestClient.ExecuteAsync(RestRequest request, CancellationToken cancellationToken)
         at DPAForPRODUCTNAMEREMOVEDBlazor.Controllers.PRODUCTNAMEREMOVED.DownloadPRODUCTNAMEREMOVEDJSON(Boolean forceDownload) in /Users/christian/projects/Insights-and-Services-for-PRODUCTNAMEREMOVED/DPAForPRODUCTNAMEREMOVEDBlazor/Controllers/PRODUCTNAMEREMOVED.cs:line 297
         at DPAForPRODUCTNAMEREMOVEDBlazor.Controllers.PRODUCTNAMEREMOVED.DownloadPRODUCTNAMEREMOVEDJSON() in /Users/christian/projects/Insights-and-Services-for-PRODUCTNAMEREMOVED/DPAForPRODUCTNAMEREMOVEDBlazor/Controllers/PRODUCTNAMEREMOVED.cs:line 198
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit '3hFrvBILVAv_71c7LL_TtxPkV0PGJNviJWzjwzYOQgQ'.

System.ArgumentException: The value cannot be null or empty. (Parameter 'mediaType')
   at System.Net.Http.Headers.MediaTypeHeaderValue.CheckMediaTypeFormat(String mediaType, String parameterName)
   at System.Net.Http.StringContent..ctor(String content, Encoding encoding, String mediaType)
   at RestSharp.RequestContent.AddPostParameters(ParametersCollection postParameters)
   at RestSharp.RequestContent.BuildContent()
   at RestSharp.RestClient.ExecuteInternal(RestRequest request, CancellationToken cancellationToken)
   at RestSharp.RestClient.ExecuteAsync(RestRequest request, CancellationToken cancellationToken)
   at DPAForPRODUCTNAMEREMOVEDBlazor.Controllers.PRODUCTNAMEREMOVED.DownloadPRODUCTNAMEREMOVEDJSON(Boolean forceDownload) in /Users/christian/projects/Insights-and-Services-for-PRODUCTNAMEREMOVED/DPAForPRODUCTNAMEREMOVEDBlazor/Controllers/PRODUCTNAMEREMOVED.cs:line 297
   at DPAForPRODUCTNAMEREMOVEDBlazor.Controllers.PRODUCTNAMEREMOVED.DownloadPRODUCTNAMEREMOVEDJSON() in /Users/christian/projects/Insights-and-Services-for-PRODUCTNAMEREMOVED/DPAForPRODUCTNAMEREMOVEDBlazor/Controllers/PRODUCTNAMEREMOVED.cs:line 198
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.0.1
 - .NET version .NET 7.0.100
 - Version 108.0.2

**Additional context**
none

**Comment by alexeyzimarev** [comment]
Sorry but the issue doesn't tell enough to diagnose the problem or even understand what the problem is. Please provide more details following the issue template.

**Comment by cheindel** [comment]
@alexeyzimarev Sorry, I was in a rush. I hope it is more clear now.

**Comment by nesc58** [comment]
When changing the TargetFrameworks of RestSharp to `net7.0` the error occurs in MultipartFormDataTests as well.

I have looked at the microsoft implementation and there are some changes.

.net6.0 implements a check to use the DefaultMediaType fallback when the given mediaType is null.

```
public StringContent(string content, Encoding? encoding, string? mediaType) : base(GetContentByteArray(content, encoding))
{
    // Initialize the 'Content-Type' header with information provided by parameters.
    MediaTypeHeaderValue headerValue = new MediaTypeHeaderValue((mediaType == null) ? DefaultMediaType : mediaType);
    headerValue.CharSet = (encoding == null) ? HttpContent.DefaultStringEncoding.WebName : encoding.WebName;
    Headers.ContentType = headerValue;
}
```

.net7.0 deimplements the check and changed the method signature (questionmark is removed)
```
public StringContent(string content, Encoding? encoding, string mediaType) : this(content, encoding, new MediaTypeHeaderValue(mediaType, (encoding ?? DefaultStringEncoding).WebName))
{
}
```

**Comment by alexeyzimarev** [comment]
.NET seven will be added as a direct target for v109 and will be executing tests for the target SDKs in the pipeline. We'll see what fails and what requires fixing.

Thanks for reporting. I haven't seen this particular one in the list of breaking changes. I guess, in time we might get more of those, unfortunately.

**Comment by alexeyzimarev** [comment]
Ok, basically the fix is to provide the default value for the `Parameter.ContentType` property.

**Comment by jhudsonWA** [comment]
<img width="917" alt="image" src="https://user-images.githubusercontent.com/702446/202225919-0fc0771e-7aa7-4a4b-9a2f-7de12c4b6457.png">

This still fails with the mediaType error. I also tried to pass in the actual type "application/pdf" and same error. Again my issue is a different path to get the same error.

**Comment by alexeyzimarev** [comment]
I haven't seen failed tests with files. I only reproduced the multipart form issue, and the workaround applies there.

I will double check the tests for `AddFile` but I haven't seen anything breaking there.

**Comment by alexeyzimarev** [comment]
@jhudsonWA you can start by looking at current tests that use `AddFile`.

**Comment by jhudsonWA** [comment]
Ok, I was barking up the wrong tree.  AddFile does work great. AddFile on a request along with other post data is a Multipart Form Data situation and would run into this bug. I tested adding the latest in 109 (compiled from the source) and the issue is confirmed fixed.

**Comment by cheindel** [comment]
I can confirm that the issue in my project is resolved with RestSharp 109.0.0-preview.1
Thank you for the quick fix @alexeyzimarev !

**Comment by RudiSzalai** [comment]
> Parameter.ContentType



> Ok, basically the fix is to provide the default value for the `Parameter.ContentType` property.

How? Could someone be so kind to help with a piece of practical and useable advice?

**Comment by alexeyzimarev** [comment]
It's shown right there https://github.com/restsharp/RestSharp/issues/1969#issuecomment-1317222476

**Comment by RudiSzalai** [comment]
the AddParameter doesn't have contentType. That's where I suck up. (the AddFile has)
![image](https://user-images.githubusercontent.com/80055828/228300820-49296cb5-c258-44e0-b1d6-ee8213260c9c.png)
