### ISSUE TITLE
No support for .net 6 TimeOnly or DateOnly objects?

### ISSUE THREAD

**Issue by grofit** [restsharp/RestSharp#2003]
**Describe the bug**
I am doing `restClient.ExecuteAsync(restRequest);` to an endpoint which expects and returns an object with `TimeOnly` field, and when this happens I get the error:

`Serialization and deserialization of 'System.TimeOnly' instances are not supported.`

I assume the error is coming from the lower layers from an existing serialization class but I couldnt find any issues on it raised so far so hopefully if others get same error posting a solution/workaround would help them too.

**To Reproduce**
Make a request to an endpoint which uses `TimeOnly` or `DateOnly` objects.

**Expected behavior**
I would expect there to be no error and the request/response is correctly serializes/deserialized.

**Stack trace**
```
System.NotSupportedException
Serialization and deserialization of 'System.TimeOnly' instances are not supported. Path: $.StartTime.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, NotSupportedException ex)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at RestSharp.Serializers.Json.SystemTextJsonSerializer.Serialize(Object obj)
   at RestSharp.Serializers.Json.SystemTextJsonSerializer.Serialize(Parameter bodyParameter)
   at RestSharp.RequestContent.<Serialize>g__GetSerialized|10_1(<>c__DisplayClass10_0& )
   at RestSharp.RequestContent.Serialize(BodyParameter body)
   at RestSharp.RequestContent.AddBody(Boolean hasPostParameters)
   at RestSharp.RequestContent.BuildContent()
   at RestSharp.RestClient.ExecuteInternal(RestRequest request, CancellationToken cancellationToken)
   at RestSharp.RestClient.ExecuteAsync(RestRequest request, CancellationToken cancellationToken)
```

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - .NET version: 6.0
 - Version: 108.0.3

**Additional context**

**Comment by grofit** [comment]
Just as a work around for others, if you MANUALLY include a newer version `System.Text.Json` via nuget it will work as expected (I am using 7.0.1) but hopefully if the implicit dependency can be updated this will solve the issue without the work around.

**Comment by alexeyzimarev** [comment]
That's basically what you should do as RestSharp only sets the lowest version restriction. Setting it to 7.0.1 would break RestSharp for everyone who cannot update the S.Text.Json package for some reason.

**Comment by grofit** [comment]
Thanks for confirming I will mark as closed
