### ISSUE TITLE
Call downloadData leads to out of memory exception

### ISSUE THREAD

**Issue by devmktb** [restsharp/RestSharp#2088]
I have facing System.OutOfMemoryException which is occurring in case I try to download some file (26mb) while the memory available is larger than the download file as many times (1gb). Any idea.

**Details:** Desktop / Windows Server 2019 / .Net 7 / C# / RestSharp / x86

**Place of the exception:**
```
RestClient client= new RestClient(BaseUrlApi, c => c.MaxTimeout = 60 * 1000);
RestRequest request = new RestRequest(path);
var file = client.DownloadData(request); // System.OutOfMemoryException 
```

**Stack trace**
```
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at RestSharp.Extensions.StreamExtensions.<ReadAsBytes>d__0.MoveNext()
   at RestSharp.RestClientExtensions.<DownloadDataAsync>d__28.MoveNext()
   at RestSharp.RestClientExtensions.<DownloadDataAsync>d__28.MoveNext()
   at RestSharp.AsyncHelpers.<>c__DisplayClass1_0`1.<<RunSync>b__0>d.MoveNext()
   at RestSharp.AsyncHelpers.CustomSynchronizationContext.<<Run>g__PostCallback|7_0>d.MoveNext()
   at RestSharp.AsyncHelpers.CustomSynchronizationContext.Run()
   at RestSharp.AsyncHelpers.RunSync(Func`1 task)
   at RestSharp.AsyncHelpers.RunSync[T](Func`1 task)
   at RestSharp.RestClientSyncExtensions.DownloadData(RestClient client, RestRequest request) 
```

Regards.

**Comment by devmktb** [comment]
I found this useful solution which solved that problem.
[HttpclientProgressExtensions](https://gist.github.com/dalexsoto/9fd3c5bdbe9f61a717d47c5843384d11)
Regards

**Comment by alexeyzimarev** [comment]
I am not sure why you are getting an OOM for a relatively small file, but `DownloadData` is still meant for small files as it loads the whole response to memory. It is nothing more than a wrapper around `DownloadStreamAsync`, which returns a stream, and you would prefer using it instead.
