### ISSUE TITLE
Client constructor throws exception

### ISSUE THREAD

**Issue by djmiek** [restsharp/RestSharp#2148]
**DO NOT USE ISSUES FOR QUESTIONS**

**Describe the bug**
When trying to create a instance of the client it throws an exception. I have tried multiple version of the tool but same error. 

**To Reproduce**
Unsure

**Stack trace**
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at RestSharp.Serializers.SerializerConfig.<>c__5`1.<UseSerializer>b__5_0()
   at RestSharp.Serializers.SerializerConfig.UseSerializer(Func`1 serializerFactory)
   at RestSharp.RestClient.ConfigureSerializers(ConfigureSerialization configureSerialization)
   at RestSharp.RestClient..ctor(RestClientOptions options, ConfigureHeaders configureDefaultHeaders, ConfigureSerialization configureSerialization, Boolean useClientFactory)
   at RestSharp.RestClient..ctor(String baseUrl, ConfigureRestClient configureRestClient, ConfigureHeaders configureDefaultHeaders, ConfigureSerialization configureSerialization)
   at Tools.ToolResendEntitiesByType.Helper.SendJson(IntegrationMessage message, SystemIdOutbound outbound, String url, String subscriptionKey)

**Desktop (please complete the following information):**
Running in Inriver IPMC cloud

**Additional context**
Here is the code that throws the exception. We have another tool that uses almost identical code that does work

string jsonString = JsonConvert.SerializeObject(message);

var client = new RestClient(url); 
client.AddDefaultHeader("Subscription-Key", subscriptionKey); 

RestRequest request = new RestRequest
{
    Method = Method.POST
};

request.AddJsonBody(jsonString);

Its the var client = new RestClient(url); that seems to not work for some reason.

**Comment by alexeyzimarev** [comment]
It's confusing issue because the code is for the old RestSharp version, the exception is from the new version, and there's no actual exception message. Creating new client instances _works_. The default serialisation configuration is applied automatically. I could _guess_ (as there's no exception message, just a stack trace) is that your runtime fails to create the default JSON serialiser instance because of missing dependency (`System.Text.Json`). I am afraid you'll have to diagnose the app packaging and runtime issues yousrelf as it's not related to the library but to your execution environment.
