### ISSUE TITLE
In latest version of RestSharp from 106.12.0 to 111.3.0 has error Null reference exception at Execute

### ISSUE THREAD

**Issue by tauqeer15** [restsharp/RestSharp#2242]
Getting Error

```
   at RestSharp.HttpRequestMessageExtensions.<AddHeaders>g__AddHeader|0_2(Parameter parameter, HttpHeaders httpHeaders)
   at RestSharp.HttpRequestMessageExtensions.<>c__DisplayClass0_0.<AddHeaders>b__1(Parameter x)
   at RestSharp.Extensions.CollectionExtensions.ForEach[T](IEnumerable`1 items, Action`1 action)
   at RestSharp.HttpRequestMessageExtensions.AddHeaders(HttpRequestMessage message, RequestHeaders headers)
   at RestSharp.RestClient.<ExecuteRequestAsync>d__5.MoveNext()
   at RestSharp.RestClient.<ExecuteAsync>d__1.MoveNext()
   at RestSharp.AsyncHelpers.<>c__DisplayClass1_0`1.<<RunSync>b__0>d.MoveNext()
   at RestSharp.AsyncHelpers.CustomSynchronizationContext.<<Run>g__PostCallback|7_0>d.MoveNext()
   at RestSharp.AsyncHelpers.CustomSynchronizationContext.Run()
   at RestSharp.AsyncHelpers.RunSync(Func`1 task)
   at RestSharp.AsyncHelpers.RunSync[T](Func`1 task)
   at RestSharp.RestClientExtensions.Execute(IRestClient client, RestRequest request)
```

**Code Snippet:**
I made changes to `RestResponse` earlier it was `IRestResponse`

```
RestRequest request = GetRequestObject(alertNotificationTransfer);
RetryPolicy<RestResponse> policy = Policy.HandleResult<RestResponse>(x => x.StatusCode != HttpStatusCode.Created)
    .WaitAndRetry(myRetryCount, retryAttempt => TimeSpan.FromSeconds(myWaitIntervalInSeconds));
var response = policy.Execute(() => myRestClient.Execute(request));

internal RestRequest GetRequestObject(NotificationTransfer alertNotificationTransfer)
{
    var request = new RestRequest(GetEnvironmentVariable(myRelativeUrlKey), Method.Post);
    request.RequestFormat = DataFormat.Json;
    request.AddJsonBody(alertNotificationTransfer);
    return request;
}
```

**Comment by alexeyzimarev** [comment]
You are adding some header with null as value and it crashes. The latest version has been made to throw earlier, when you add a header with null value.
