### ISSUE TITLE
Update references for System.Text.Json

### ISSUE THREAD

**Issue by albgen** [restsharp/RestSharp#2277]
**Describe the bug**
The latest version of Restsharp is referencing the version 8.0.0.4 of System.Text.Json
This means that i can't update the System.Text.Json because it will break the dependency.

**To Reproduce**
Use Restsharp latest version and also reference to latest version of System.Text.Json.

**Expected behavior**
Load the latest assembly of System.Text.Json

**Stack trace**
A call to devPOS.Fiskalizimi.Client.GlobalConfiguration.AccessToken failed with this message: **Could not load file or assembly** 'System.Text.Json, Version=8.0.0.4, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NavDotNet.Invoke[T](String methodName, UInt32 methodIndex, BindingFlags flags, ParameterModifier modifier, Type[] referenceTypes, Object[] arguments)
   at Microsoft.Dynamics.Nav.Runtime.NavDotNet.InvokePropertyGet[T](Boolean isStatic, String propertyName, UInt32 methodIndex)
   at Microsoft.Dynamics.Nav.Runtime.NavDotNet.InvokePropertyGet[T](String propertyName, UInt32 methodIndex)..etc

**Desktop (please complete the following information):**
 - OS: Windows
 - .NET FRamework 4.8
 - Version 112.1

**Comment by d-a-s** [comment]
Also having this problem. Even though I'm telling it to use newtonsoft, it's still trying to specifically load 8.0.0.4 of System.Text.Json.
```
_client = new RestClient(options, configureSerialization: s =>
{
    s.UseNewtonsoftJson();
});
```

**Comment by clburkins** [comment]
Also have this bug. Has anyone come up with a workaround? At this point, I'm considering looking for an alternative to RestSharp, but I'd really rather not.

**Comment by d-a-s** [comment]
The latest `112.1.1-alpha.0.4` release does fix the problem. No idea why they haven't done a stable release, but you can at least use the alpha. Nuget has instructions on how to use the CLI or package manager to add the alpha.

https://www.nuget.org/packages/RestSharp/112.1.1-alpha.0.4

**Comment by clburkins** [comment]
d-a-s thank you. I had just checked out the code to see if I could fix it myself, but I'll try that first. (Though I have to admit that seeing if I could fix it still could be fun!)

**Comment by Shujee** [comment]
Just checking back if this is a plan to merge `112.1.1-alpha.0.4` into the stable channel anytime soon.
