### ISSUE TITLE
Unable to post message on Windows Compact Framework

### ISSUE THREAD

**Issue by ylupien** [restsharp/RestSharp#511]
When I try to use this library under Windows Mobile 6.5 Device the library fail posting message due an exception of Content-Length: -1

```
{System.InvalidOperationException: Either ContentLength must be set to a non-negative number, or SendChunked set to true in order to perform the write operation when AllowWriteStreamBuffering is disabled.
   at System.Net.HttpWebRequest.startGetRequestStream()
   at System.Net.HttpWebRequest.BeginGetRequestStream(AsyncCallback callback, Object state)
   at RestSharp.Http.WriteRequestBodyAsync(HttpWebRequest webRequest, Action`1 callback)
   at RestSharp.Http.PutPostInternalAsync(String method, Action`1 callback)
   at RestSharp.Http.AsPostAsync(Action`1 action, String httpMethod)
   at RestSharp.RestClient.DoAsPostAsync(IHttp http, Action`1 response_cb, String method)
   at RestSharp.RestClient.ExecuteAsync(IRestRequest request, Action`2 callback, String httpMethod, Func`4 getWebRequest)
   at RestSharp.RestClient.ExecuteAsync(IRestRequest request, Action`2 callback)
   at RestSharp.RestClientExtensions.ExecuteAsync(IRestClient client, IRestRequest request, Action`1 callback)
   at SmartDeviceProject1.Form1.button2_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.ButtonBase.WnProc(WM wm, Int32 wParam, Int32 lParam)
   at System.Windows.Forms.Control._InternalWnProc(WM wm, Int32 wParam, Int32 lParam)
   at Microsoft.AGL.Forms.EVL.EnterMainLoop(IntPtr hwnMain)
   at System.Windows.Forms.Application.Run(Form fm)
   at SmartDeviceProject1.Program.Main()
}
```

When I debug I realize there is a pre parser condition that avoid calculating document content size for WINDOWS_PHONE and  PocketPC

In file Http.Async.cs under function WriteRequestBodyAsync()

``` csharp
#if !WINDOWS_PHONE && !PocketPC
  webRequest.ContentLength = CalculateContentLength();
#endif
```

Posting of message succeeded when I remove !PocketPC

**Comment by alexeyzimarev** [comment]
These conditionals have been removed when moving to .NET Standard.
