### ISSUE TITLE
No parameterless constructor defined for this object on arrays & enumerables of simple types

### ISSUE THREAD

**Issue by synhershko** [restsharp/RestSharp#547]
The following error is thrown when `Execute<T>()` is called with T having `string[]`, `IEnumerable<T>` and similar.

This seems rather easy to fix on the JsonDeserializer, I wonder if it wasn't done on purpose?

Let me know if I should send a PR with a fix

```
System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at RestSharp.Deserializers.JsonDeserializer.CreateAndMap(Type type, Object element)
   at RestSharp.Deserializers.JsonDeserializer.ConvertValue(Type type, Object value)
   at RestSharp.Deserializers.JsonDeserializer.Map(Object target, IDictionary`2 data)
   at RestSharp.Deserializers.JsonDeserializer.CreateAndMap(Type type, Object element)
   at RestSharp.Deserializers.JsonDeserializer.ConvertValue(Type type, Object value)
   at RestSharp.Deserializers.JsonDeserializer.Map(Object target, IDictionary`2 data)
   at RestSharp.Deserializers.JsonDeserializer.CreateAndMap(Type type, Object element)
   at RestSharp.Deserializers.JsonDeserializer.ConvertValue(Type type, Object value)
   at RestSharp.Deserializers.JsonDeserializer.BuildList(Type type, Object parent)
   at RestSharp.Deserializers.JsonDeserializer.ConvertValue(Type type, Object value)
   at RestSharp.Deserializers.JsonDeserializer.Map(Object target, IDictionary`2 data)
   at RestSharp.Deserializers.JsonDeserializer.CreateAndMap(Type type, Object element)
   at RestSharp.Deserializers.JsonDeserializer.ConvertValue(Type type, Object value)
   at RestSharp.Deserializers.JsonDeserializer.Map(Object target, IDictionary`2 data)
   at RestSharp.Deserializers.JsonDeserializer.Deserialize[T](IRestResponse response)
   at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)
```

**Comment by nadirakdag** [comment]
this error about arrays if you convert your arrays to list you can escape this error. 
First version
public object[] sizes { get; set; }

Right version
public List<object> sizes { get; set; }

**Comment by urig** [comment]
+1 for including this feature in the built-in JSON deserializer. 

Deserializing arrays is basic scenario for consuming REST APIs. IMHO RestSharp users, especially inexperienced ones, should not have to  invest effort in custom serialization for something so trivial.

**Comment by ismoli** [comment]
Just spent an hour trying to understand the reason for exception which literally says  "No parameterless constructor defined for this object." Not a hint on what actually "this" object is. Stack trace is also not helpful. And my object is big. And all children got constructors... 
Couldn't even believe my eyes when found this thread.  Serializing arrays is something you expect from JSON serializer, period.

At least make exception more detailed... You don't usually search for a constructors on arrays :)

Also the number of people watching this issue is quite indicative...

**Comment by Workshop2** [comment]
+1 - I can't believe I have to use Lists when I don't need them :unamused:

**Comment by Lechus** [comment]
Even with List<T> id gives me "No parameterless constructor defined for this object."

**Comment by hallem** [comment]
right, you have to make a class and then include the list or array or etc. as apart of it for things to work right now.  making the change to allow this to happen with the default de/serializer just isn't possible.  i have a work item in progress to go back to using JSON.NET as the de/serializer and that should make this a lot easier.

**Comment by kierenj** [comment]
Has my vote too.  A `List<>`, which seems to be required at the moment, tells consumers of the type that items can be added to it and removed from it.  I believe that deserialising a JSON array should at least work with the equivalent C# type - which is an array, not a `List`.

**Comment by mot256** [comment]
Ran into the same problem with the default XmlDeserializer when deserializing XML payloads. Replaced the XML serializer with DotNetXmlDeserializer and it worked fine.

**Comment by arteny** [comment]
I am getting same error even for reference type data list:
			var res = _restClient.Execute<List<MyData>>(restRequest);

**Comment by Rajkumar-Raj** [comment]
Alternative solution:

var res = _restClient.Execute(restRequest);
var obj = JsonConvert.DeserializeObject<RootObject>(res.Content); 

Using Visual studio (visual studio -> Edit -> Paste Special ->Paste Json to Classes) create rootobject and Use Newtonsoft.json dll to convert Json data to Object

**Comment by alexeyzimarev** [comment]
We will not be able to change the code os SimpleJson. Work is being done to support alternative serialisers easier. Track #1018.

**Comment by boston99green** [comment]
I had the same issue with string[], I solved it this way.
   var response = client.Execute(request);
   var responseData = JsonConvert.DeserializeObject<Person>(response.Content);

**Comment by anapro-charles** [comment]
> this error about arrays if you convert your arrays to list you can escape this error.
> First version
> public object[] sizes { get; set; }
> 
> Right version
> public List sizes { get; set; }

Thanks

**Comment by zaus** [comment]
Can you just internally deserialize the array as a List and then...turn it back or something?  I think I traced the issue to `CreateAndMap`'s use of `Activator.CreateInstance(type);`.  Or more likely in `ConvertValue` add a _BuildArray_ method like the _BuildList_ check.

**Comment by sicklittlemonkey** [comment]
Some of us have to deal with old (105.x) versions for Reasons™. In my case I had to make two changes.

```
// Change this IEnumerable:
	public class SomeResult : SomeBaseResult
	{
		public IEnumerable<Thing> Things { get; set; }
	}
// To List:
	public class SomeResult : SomeBaseResult
	{
		public List<Thing> Things { get; set; }
	}
// And:
	public class Thing
	{
		public Thing() {} // Add this parameter-less constructor
		public Thing(...)
		{
			// ...
		}
		// ...
	}

```
