### ISSUE TITLE
POST requests without body throws exception

### ISSUE THREAD

**Issue by Grazzling** [restsharp/RestSharp#700]
Hello,

when trying to send a POST request without any actual body, RestSharp throws the following exception:

```
System.ArgumentNullException: String reference not set to an instance of a String.
    at System.Text.Encoding.GetBytes(String s)
    at RestSharp.Http.WriteStringTo(Stream stream, String toWrite)
    at RestSharp.Http.WriteRequestBody(HttpWebRequest webRequest)
    at RestSharp.Http.PostPutInternal(String method)
    at RestSharp.Http.AsPost(String httpMethod)
    at RestSharp.RestClient.DoExecuteAsPost(IHttp http, String method)
    at RestSharp.RestClient.Execute(IRestRequest request, String httpMethod, Func`3 getResponse)
```

In **Http.Sync.cs**:

```
private void WriteRequestBody(HttpWebRequest webRequest)
{
    if (HasBody || HasFiles || AlwaysMultipartFormData)
    {
#if !WINDOWS_PHONE && !PocketPC
        webRequest.ContentLength = CalculateContentLength();
#endif
    }

    using (var requestStream = webRequest.GetRequestStream())
    {
        if (HasFiles || AlwaysMultipartFormData)
        {
            WriteMultipartFormData(requestStream);
        }
        else if (RequestBodyBytes != null)
        {
            requestStream.Write(RequestBodyBytes, 0, RequestBodyBytes.Length);
        }
        else
        {
            WriteStringTo(requestStream, RequestBody);
        }
    }
}
```

The last else-branch is executed even when *RequestBody* is null.

For reference, here is the simple code snippet that triggers the exception:

```
//...
RestRequest request = new RestRequest("_api/contextinfo");
request.Method = Method.POST;
request.AddHeader("Accept", "text/xml; odata=verbose");

IRestResponse response = client.Execute(request);
//...
```

Best regards

**Comment by hallem** [comment]
Nice catch.  I'll get this fixed.

**Comment by alexeyzimarev** [comment]
It’s fixed by now
